title: Podcast Mozilla Brasil
url: "http://podcast.mozillabrasil.org.br"

description: "Podcast da comunidade Mozilla Brasil sobre o Firefox, Thunderbird e Webmaker, assim como todo os outros produtos da Mozilla e seu manifesto."

timezone:    America/Sao_Paulo
permalink:   /:title/
markdown: kramdown

locale: pt-BR

managingeditormail: podcast@mozillabrasil.org.br
webmastermail: podcast@mozillabrasil.org.br

feedttl: 1440

paginate: 5

assetsserver: "http://dl.mozillabrasil.org.br/podcast"

port: 7666
